package com.growup.pms.role.domain;

public enum PermissionType {
    // TEAM
    TEAM_DELETE,
    TEAM_UPDATE,
    // TEAM_MEMBER
    TEAM_KICK_MEMBER,
    TEAM_MEMBER_ROLE_UPDATE,
    TEAM_INVITE_MEMBER,
    // PROJECT
    TEAM_PROJECT_CREATE,
    PROJECT_UPDATE,
    PROJECT_DELETE,
    // PROJECT_MEMBER
    PROJECT_KICK_MEMBER,
    PROJECT_MEMBER_ROLE_UPDATE,
    PROJECT_INVITE_MEMBER,
    // STATUS
    PROJECT_STATUS_READ,
    PROJECT_STATUS_WRITE,
    PROJECT_STATUS_UPDATE,
    PROJECT_STATUS_DELETE,
    // TASK
    PROJECT_TASK_READ,
    PROJECT_TASK_WRITE,
    PROJECT_TASK_UPDATE,
    PROJECT_TASK_DELETE,
}
