package com.growup.pms.role.domain;

public enum PermissionType {
    TEAM_DELETE,
    TEAM_UPDATE,
    TEAM_KICK_MEMBER,
    TEAM_MEMBER_ROLE_UPDATE,
    TEAM_INVITE_MEMBER,
    PROJECT_STATUS_READ,
    PROJECT_STATUS_WRITE,
    PROJECT_STATUS_UPDATE,
    PROJECT_STATUS_DELETE,
    PROJECT_TASK_READ,
    PROJECT_TASK_WRITE,
    PROJECT_TASK_UPDATE,
    PROJECT_TASK_DELETE,
}
