spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ENC(gO8UhZghCEeTIIcPyUXJ2iodj/+DaESNIBfQNc8z5BgjjnsJDHlzGsEN/PQKeFTfGUi4DpNDMyxAWb9qpQICv6oE4Zcr0wKUsuElfoenGh45KVB18hJUZ+mKsL6BFsfKk2MG29hb7X2RzMTEKz3WS6maXNu2rZwL563kMPASqPk=)
    username: ENC(sgyx0VySXTe4KnQtUqUhRLPpBa1iT/mCBZWGGV9/5LcWgpONx3fpebGP9UinHU4v)
    password: ENC(5mM3YfiCkMnkgpwYHn6r9HEd0q6yTqHN+zAInH/rm9JezFqxVrP94Iy2Mzrx0SrtyN7Dc+tjHSqZHsDVGYyXTA==)

  jpa:
    hibernate:
      # FIXME: 추후에 서비스 개발이 끝나고 배포 환경이 구성되면 validate 혹은 none으로 변경해야 함
      ddl-auto: create

  data:
    redis:
      host: redis
      port: 6379

discord:
  webhook:
    url: ${DISCORD_WEBHOOK_URL}
    username: Error Reporter
    avatar-url: https://i.imgur.com/uRkHXjk.png

management:
  endpoints:
    web:
      exposure:
        include: ["prometheus"]

  endpoint:
    prometheus:
      enabled: true

    metrics:
      enabled: true

  prometheus:
    metrics:
      export:
        enabled: true

aws:
  access-key: ENC(e6gMLdiSQvEgCqzQ7JRDNosVbW//CnDVkV8caxgYwfb8MEm5lj8m0fsc8I2bxsaEReR1BoIPxI0qISJ+sgxm5g==)
  secret-key: ENC(Z835JZnyCMeatP7CdJDrWiCqaNr2jsNFhCCWc5MhkVfMM3WwUt6wMqKOfuvV83jYuSEJqfBdcrBScNH9B7XUT+DFXfta4/G0MpsBOl7kuZM=)
  s3:
    region: ENC(u9xNdlCO2E+c+SOkV5wcv0pA2h3I5K5LGCy0qKmziQQJBop6PvKWpn6VZb35EJsv)
    bucket-name: ENC(n9BhDd0eubOZLL7wWEBmsfC/okUQwUDzqJWuU4bXtIR9d3i3LstwERRxTWnekLopl4KgKw5h7CJQ5Jpm/fSdmQ==)

oauth2:
  kakao:
    clientId: ENC(lU3WDCJvRNuPhLlqzlhJAJR5/bnhVKlYRKgfGBu/OhsPkf+I+tsYXgQTo3J5F9xeKalQVvsBrzZXC+CeRe+N3l9cAgA7ldYmHAcEfy5A0no=)
    redirect-uri: http://growup.kr:8080/api/v1/user/login/kakao
    accessToken-request-uri: https://kauth.kakao.com/oauth/token
    userinfo-request-uri: https://kapi.kakao.com/v2/user/me

  google:
    clientId: ENC(fNrqSGUZ1XIS8cCyPlved2E4LhAkhUA/hSNGGr3+QAxYcGxKqnOuDVO+mVQ6bynpHcWCKS1ejijZ/coeMzL9fwbgJWcrnWqT/VrzOrSKDiSwnMJuy6ZyQGW7DAsrqT/3Un5DemmfuDfcplS1vWZ7oA==)
    clientSecret: ENC(sx7EcQL+9+wE0QTlmpF24t1EX+nr9yndtQmrmJbqxOIzGsC/TLR8mA5W78YCotRfmEBCmlGr6vEWta9FrXqP2D4rENLlHIuZx97Upih1LPg=)
    redirect-uri: http://growup.kr:8080/api/v1/user/login/google
    scope: https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile
    accessToken-request-uri: https://oauth2.googleapis.com/token
    userinfo-request-uri: https://www.googleapis.com/oauth2/v2/userinfo
