spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:pms;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true

  h2:
    console:
      enabled: true
      path: /h2-console

  sql:
    init:
      mode: always
      platform: local

  data:
    redis:
      host: localhost
      port: 6379

oauth2:
  kakao:
    clientId: ENC(qhz/1p8n/EFFSF3APlmBYtiYGnokE0bYAxMSpSz0PTKeAgUN1+jTzGvgWGKdg+otmxXlRNRTYMyOe07XcviMpLkNruEnggMpLZnQE7Z4/fs=)
    redirect-uri: http://localhost:5173/auth/kakao/callback
    accessToken-request-uri: https://kauth.kakao.com/oauth/token
    userinfo-request-uri: https://kapi.kakao.com/v2/user/me

  google:
    clientId: ENC(SLlWjeaquS7YGgH7mzJElBAvgdS2MnCWVA0yirq4k5M7x1rOrjdgo5IIGgcFDa4l6ymCNskT9wxXbq1lEHSpzxvmFaaz7dUtkC/DIEnbWMAGc3QhSoaqAUEBSwzbLqWdFc6Sl1kVSCLf9/S44EXOPg==)
    clientSecret: ENC(2yXpBIfVcAPv2REJ0Wi6FVE+dI+V12dYdKCTBJKFGIcQLzzDSXAv+RJ7A8sekg1iKE4hl6MSWQdkSbLBbKVyNqa65vxYT8pAHi0qatglCFE=)
    redirect-uri: http://localhost:5173/auth/google/callback
    scope: https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile
    accessToken-request-uri: https://oauth2.googleapis.com/token
    userinfo-request-uri: https://www.googleapis.com/oauth2/v2/userinfo

aws:
  access-key: dummy-access-key
  secret-key: dummy-secret-key
  s3:
    region: dummy-region
    bucket-name: dummy-bucket-name

