spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ENC(WZHLm3GnAlU8rTxFs7SzoV5rMDScKvxijuDXUSSTWYxZXZXIn5aCY2cml6ju79ViHVDMmcGACADrTWCQfw0QjJeHftCSFTmmmtrxCjOYgXI=)
    username: ENC(LSBagAlJD17jijCc9EzIrls5cFWPJBJ1vv5UZFq2aaxMQfUdtthCZZNBcQBZ8Lgc)
    password: ENC(dGA/gmYmcGV7vk1CHj5d3q63EF4ZAm/poV9onyenaB43GUfML0J4NYBQvhte/3Sk)

  jpa:
    hibernate:
      # FIXME: 추후에 서비스 개발이 끝나고 배포 환경이 구성되면 validate 혹은 none으로 변경해야 함
      ddl-auto: create

  data:
    redis:
      host: redis
      port: 6379

discord:
  webhook:
    url: ${DISCORD_WEBHOOK_URL}
    username: Error Reporter
    avatar-url: https://i.imgur.com/uRkHXjk.png
