name: 🛠️ 리팩터링
description: 리팩터링을 해야할 부분이 있나요?
labels: ["🛠️ 리팩터링"]
projects: ["GU-99/2"]
body:
  - type: textarea
    attributes:
      label: 🛠️ 설명
      description: "리팩터링 작업에 대한 설명을 입력해주세요. 설명은 구체적일수록 좋습니다."
      placeholder: "예: 기존 사용자 관리 모듈의 코드 품질을 개선하고 성능을 최적화하기 위해 리팩터링을 진행합니다."
    validations:
      required: true

  - type: textarea
    attributes:
      label: ✅ 작업할 내용
      description: "리팩터링을 할 부분에 대한 작업들을 작성해 주세요."
      placeholder: |
        - [ ] 코드 중복 제거
        - [ ] 변수 및 함수명 의미 있게 변경
        - [ ] 오래된 라이브러리 최신 버전으로 업데이트
        - [ ] 불필요한 주석 제거
        - [ ] 단위 테스트 추가 및 수정
    validations:
      required: true

  - type: textarea
    attributes:
      label: 📚 참고 자료
      description: "작업과 관련해서 참고할 만한 자료나 링크가 있다면 제공해주세요."
      placeholder: "참고할 자료나 링크를 입력해주세요."
    validations:
      required: false

  - type: input
    attributes:
      label: ⏰ 추정 시간
      description: "리팩토링 작업에 예상되는 소요 시간을 입력해주세요."
      placeholder: "예: 1시간"
    validations:
      required: true

  - type: input
    attributes:
      label: ⏰ 소요 시간
      description: "리팩토링 작업에 실제로 소요된 시간을 입력해주세요."
      placeholder: "예: 1.5시간"
    validations:
      required: false
