global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring-boot-prometheus'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:8080']
