name: PR Test Validation

on:
  pull_request:
  push:
    branches:
      - main
      - develop

jobs:
  pr-test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v4
        with:
          # Limiting history to PR commits only; full history scan seems excessive for Qodana
          fetch-depth: ${{ github.event.pull_request.commits }}

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run tests with Gradle
        run: ./gradlew test --no-daemon

      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2024.1
        with:
          cache-default-branch-only: true
          # NOTE: Temporary workaround for inefficient caching.
          # Using a generic cache key to reduce redundant downloads across PRs.
          additional-cache-key: qodana-2024.1-
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
