name: Update Cache

on:
  push:
    branches:
      - main
      - develop

jobs:
  update-cache:
    runs-on: ubuntu-latest
    env:
      # Constants to ensure cache key matches setup-java action
      CACHE_KEY_PREFIX: setup-java
      PACKAGE_MANAGER: gradle
    steps:
      - uses: actions/checkout@v4
      # Save the Gradle cache with a key matching the setup-java action's cache key pattern
      # Reference: https://github.com/actions/setup-java/blob/2e74cbce18569d23ca8b812590dbb83f13ac7c5a/src/cache.ts#L101
      - name: Save Gradle cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ env.CACHE_KEY_PREFIX }}-${{ runner.os }}-${{ env.PACKAGE_MANAGER }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
