name: Update Cache

on:
  push:
    branches:
      - main
      - develop
    paths-ignore:
      - '.github/**'
      - 'styleguide/**'
      - '.editorconfig'

jobs:
  update-cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: 'gradle'
